contact_links:
  - name: "ğŸš€ Join the Algo Community"
    url: "https://forms.gle/8EpYfRgVmrDxXAio6"
    about: >
      âœ¨ If you would like to join the Algo community, please fill out the form to request an invitation.
      Provide details about your skills and motivation for joining. We will review your request and 
      send an invitation if approved.
  - name: "ğŸ‘¥ Join the Algo Community on LinkedIn"
    url: "https://www.linkedin.com/groups/14536479/"
    about: "ğŸŒ Join our LinkedIn group to connect with fellow developers, discuss data structures and algorithms, and grow your skills together."
